# 基础 

## ndarray

### 建立和方法

In [2]:
import numpy as np
data=[[1,2,3,4],[5,6,7,8]]
arr=np.array(data)
print(arr)a

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
arr.shape

(2, 4)

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.empty((3,6))#empty的返回值有可能会是任意值

array([[6.95332204e-310, 6.95332204e-310, 8.90301763e+247,
        6.01347002e-154, 1.96086579e+243, 4.70107982e+180],
       [1.23542248e-259, 6.01347002e-154, 4.38890771e+156,
        5.81236387e+180, 1.81363726e-152, 4.70107982e+180],
       [1.23542248e-259, 4.14319293e+199, 6.01346954e-154,
        2.44041296e-154, 5.55603543e+180, 5.98189082e-154]])

In [12]:
np.empty_like(np.empty((3,6)))

array([[6.95332204e-310, 6.95332204e-310, 8.90301763e+247,
        6.01347002e-154, 1.96086579e+243, 4.70107982e+180],
       [1.23542248e-259, 6.01347002e-154, 4.38890771e+156,
        5.81236387e+180, 1.81363726e-152, 4.70107982e+180],
       [1.23542248e-259, 4.14319293e+199, 6.01346954e-154,
        2.44041296e-154, 5.55603543e+180, 5.98189082e-154]])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [19]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
np.identity(10)#等价于eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### 控制存储类型

In [23]:
arr1=np.array([1,2,3],dtype=np.float64)

In [24]:
arr1

array([1., 2., 3.])

###### 直接映射到机器表示，如果要处理大数据或是控制数据在内存或磁盘中的存储方式就需要用到

In [26]:
arr=np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [28]:
float_arr=arr.astype(np.float64)
print(float_arr)
float_arr.dtype

[1. 2. 3. 4. 5.]


dtype('float64')

In [ ]:
arr=np.array([])