# PyTorch 

## Basics

### Tensors

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)
x = torch.rand(5, 3)
print(x)
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
x = torch.tensor([5.5, 3])
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.7284, 0.8125, 0.8411],
        [0.0515, 0.2792, 0.8659],
        [0.5773, 0.2916, 0.1035],
        [0.9841, 0.0869, 0.5733],
        [0.0370, 0.7751, 0.0450]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])


In [3]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.3674,  0.8366, -0.5339],
        [ 0.1163, -0.7223, -0.9487],
        [-0.1676, -0.1579, -0.4391],
        [-0.4560, -0.8921,  1.5099],
        [ 1.4007, -1.1069,  0.4456]])


In [4]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.2481,  1.3827,  0.1875],
        [ 1.0983,  0.2051, -0.2663],
        [ 0.0126,  0.1875, -0.3306],
        [-0.0047,  0.0645,  2.0379],
        [ 1.7377, -0.2457,  1.3334]])


In [5]:
torch.add(x,y)

tensor([[-0.2481,  1.3827,  0.1875],
        [ 1.0983,  0.2051, -0.2663],
        [ 0.0126,  0.1875, -0.3306],
        [-0.0047,  0.0645,  2.0379],
        [ 1.7377, -0.2457,  1.3334]])

In [6]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)#传入了result的引用
print(result)

tensor([[-0.2481,  1.3827,  0.1875],
        [ 1.0983,  0.2051, -0.2663],
        [ 0.0126,  0.1875, -0.3306],
        [-0.0047,  0.0645,  2.0379],
        [ 1.7377, -0.2457,  1.3334]])


In [7]:
# adds x to y
#调用方法永久地改变了y的值
y.add_(x)
print(y)

tensor([[-0.2481,  1.3827,  0.1875],
        [ 1.0983,  0.2051, -0.2663],
        [ 0.0126,  0.1875, -0.3306],
        [-0.0047,  0.0645,  2.0379],
        [ 1.7377, -0.2457,  1.3334]])


Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [8]:
print(x)
print(x[:,0])

tensor([[-0.3674,  0.8366, -0.5339],
        [ 0.1163, -0.7223, -0.9487],
        [-0.1676, -0.1579, -0.4391],
        [-0.4560, -0.8921,  1.5099],
        [ 1.4007, -1.1069,  0.4456]])
tensor([-0.3674,  0.1163, -0.1676, -0.4560,  1.4007])


In [9]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [10]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7090])
0.7089889049530029


### Work with Numpy

In [21]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [28]:
#Covert Back
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA

In [27]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.7090], device='cuda:0')
tensor([1.7090], dtype=torch.float64)


## AUTOGRAD

In [29]:
import torch

### require_grad and grad_fn

In [201]:
x = torch.zeros(2, 2, requires_grad=True)
print(x)

tensor([[0., 0.],
        [0., 0.]], requires_grad=True)


In [202]:
y=x+2
print(y)
print(y.grad_fn)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [203]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[12., 12.],
        [12., 12.]], grad_fn=<MulBackward0>) tensor(12., grad_fn=<MeanBackward0>)


In [204]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.grad_fn)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

None
False
True


### Back Propagation

In [205]:
out.backward()

In [206]:
print(x.grad)

tensor([[3., 3.],
        [3., 3.]])


In [267]:
x = torch.zeros(3, requires_grad=True)

y = ((-x) * 2)**2

#此处仍然是在x的初始位置进行求导。

print(y)

v = torch.tensor([0.1,1,10], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([0., 0., 0.], grad_fn=<PowBackward0>)
tensor([0., 0., 0.])


In [96]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


## Neural Network

### Feed-Forward Network

In [268]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [269]:
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1's .weight

10
torch.Size([6, 1, 3, 3])


In [270]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0881,  0.0385,  0.0824,  0.0745,  0.0060, -0.0100,  0.1030, -0.0130,
          0.1161,  0.0714]], grad_fn=<AddmmBackward>)


In [271]:
net.zero_grad()
out.backward(torch.randn(1, 10))